[workspace]
resolver = "2"
members = [
    "boot_services",
    "guid",
    "runtime_services",
    "tpl_mutex",
    "uefi_decompress",
    "perf_timer",
]

[workspace.package]
repository = "https://github.com/microsoft/mu_rust_helpers"
license = "BSD-2-Clause-Patent"
edition = "2021"
include = [
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[workspace.dependencies]
r-efi = "5.1.0"
boot_services = { path="./boot_services" }
runtime_services = { path="./runtime_services" }
guid = { path="./guid" }
tpl_mutex = { path="./tpl_mutex" }
uefi_decompress = { path="./uefi_decompress" }
uuid = { version = "1.10.0", default-features = false}
log = "~0.4"

[package]
name = "mu_rust_helpers"
version = "1.2.0"
description = ""
repository.workspace = true
license.workspace = true
edition.workspace = true
include.workspace = true

[features]
default = ["boot_services", "runtime_services", "guid", "tpl_mutex", "uefi_decompress", "perf_timer"]
boot_services = ["dep:boot_services"]
runtime_services = ["dep:runtime_services"]
guid = ["dep:guid"]
tpl_mutex = ["dep:tpl_mutex"]
uefi_decompress = ["dep:uefi_decompress"]
perf_timer = ["dep:perf_timer"]

[dependencies]
boot_services = { path = "./boot_services", version = "1.0.0", optional = true }
guid = { path = "./guid", version = "0.1.0", optional = true }
runtime_services = { path = "./runtime_services", version = "0.1.0", optional = true }
tpl_mutex = { path = "./tpl_mutex", version = "0.1.0", optional = true }
uefi_decompress = { path = "./uefi_decompress", version = "0.1.0", optional = true }
perf_timer = { path = "./perf_timer", version = "0.1.0", optional = true }

[dev-dependencies]
r-efi = { workspace = true }
boot_services = { path = "./boot_services", features = ["mockall"]}
runtime_services = { path = "./runtime_services", features = ["mockall"]}


